after-login-command = []
after-startup-command = [ 
    'exec-and-forget defaults write com.doomlaser.cursorcerer idleHide -float 3',
    'exec-and-forget ~/.nix-profile/bin/borders active_color=0xFFEBDBB2 inactive_color=0xFF928373 width=2.0'
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        20
outer.right =      20

[exec]
inherit-env-vars = true
[exec.env-vars]
PATH = '/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}'
