#!/bin/bash

if [ "$1" == "clean" ]; then
  cd .base && stow --delete . && cd ..
  cd .linux && stow --delete . && cd ..
  cd .macos && stow --delete . && cd ..
else
  OS=$(uname -s | tr A-Z a-z)
  HOSTNAME=$(hostname -s | tr A-Z a-z)

  if [ "$OS" == "darwin" ]; then
    bash .scripts/get_brew
    brew install $(cat .packages/brew)
    cargo install $(cat .packages/cargo)
    cd .macos && stow . && cd ..
  fi

  if [ "$OS" == "linux" ]; then
    rm -rf /etc/portage
    git clone https://github.com/rraafays/$HOSTNAME /etc/portage
    emerge --quiet --update --deep --newuse @world
    emerge --quiet --noreplace $(cat .packages/emerge)
    cargo install $(cat .packages/cargo)
    cd .linux && stow . && cd ..
  fi

  rm -rf fish kitty
  cd .base && stow . && cd ..
fi
