#!/bin/bash

OS=$(uname -s | tr A-Z a-z)

if not [ "$EUID" -ne 0 ]; then
	echo "REPLICATE: please do not run with elevated permission"
	exit
fi

if [ "$OS" == "darwin" ]; then
	bash .scripts/brew_replicate
fi
if [ "$OS" == "linux" ]; then
	doas bash .scripts/emerge_replicate
fi

cargo install $(cat .packages/cargo)
bash .scripts/librewolf_replicate
