complete -c push -l all -l branches -d 'Push all branches (i. e'
complete -c push -l prune -d 'Remove remote branches that don\'t have a local counterpart'
complete -c push -l mirror -d 'Instead of naming each ref to push, specifies that all refs under refs/ (whic…'
complete -c push -s n -l dry-run -d 'Do everything except actually send the updates'
complete -c push -l porcelain -d 'Produce machine-readable output'
complete -c push -s d -l delete -d 'All listed refs are deleted from the remote repository'
complete -c push -l tags -d 'All refs under refs/tags are pushed, in addition to refspecs explicitly liste…'
complete -c push -l follow-tags -d 'Push all the refs that would be pushed without this option, and also push ann…'
complete -c push -l signed -l signed -d 'GPG-sign the push request to update refs on the receiving side, to allow it t…'
complete -c push -l atomic -d 'Use an atomic transaction on the remote side if available'
complete -c push -s o -l push-option -d 'Transmit the given string to the server, which passes them to the pre-receive…'
complete -c push -l receive-pack -l exec -d 'Path to the git-receive-pack program on the remote end'
complete -c push -l force-with-lease -l force-with-lease -l force-with-lease -d 'Usually, "git push" refuses to update a remote ref that is not an ancestor of…'
complete -c push -s f -l force -d 'Usually, the command refuses to update a remote ref that is not an ancestor o…'
complete -c push -l force-if-includes -d 'Force an update only if the tip of the remote-tracking ref has been integrate…'
complete -c push -l repo -d 'This option is equivalent to the <repository> argument'
complete -c push -s u -l set-upstream -d 'For every branch that is up to date or successfully pushed, add upstream (tra…'
complete -c push -l thin -d 'These options are passed to git-send-pack(1)'
complete -c push -s q -l quiet -d 'Suppress all output, including the listing of updated refs, unless an error o…'
complete -c push -s v -l verbose -d 'Run verbosely'
complete -c push -l progress -d 'Progress status is reported on the standard error stream by default when it i…'
complete -c push -l no-recurse-submodules -l recurse-submodules -d 'May be used to make sure all submodule commits used by the revisions to be pu…'
complete -c push -l verify -d 'Toggle the pre-push hook (see githooks(5))'
complete -c push -s 4 -l ipv4 -d 'Use IPv4 addresses only, ignoring IPv6 addresses'
complete -c push -s 6 -l ipv6 -d 'Use IPv6 addresses only, ignoring IPv4 addresses'
complete -c push -l no-signed -d 'true or'
complete -c push -l no-force-if-includes -d 'disables this behavior'
complete -c push -l no-follow-tags -d 'push. gpgSign'
