"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$status$username$hostname$battery$all"

[battery]
disabled = false

[[battery.display]]
threshold = 0
discharging_symbol = '󰂎 '
charging_symbol = '󰢟 '
style = 'fg:8'
[[battery.display]]
threshold = 20
discharging_symbol = '󰁻 '
charging_symbol = '󰂆 '
style = 'fg:8'
[[battery.display]]
threshold = 40
discharging_symbol = '󰁽 '
charging_symbol = '󰂈 '
style = 'fg:8'
[[battery.display]]
threshold = 60
discharging_symbol = '󰁿 '
charging_symbol = '󰂉 '
style = 'fg:8'
[[battery.display]]
threshold = 80
discharging_symbol = '󰂁 '
charging_symbol = '󰂊 '
style = 'fg:8'
[[battery.display]]
threshold = 100
discharging_symbol = '󰁹 '
charging_symbol = '󰂅 '
style = 'fg:8'

[character]
success_symbol = "[\\$](bold fg:2)"
error_symbol = "[\\$](bold fg:2)"
vimcmd_symbol = "[\\$](bold fg:8)"
vimcmd_replace_one_symbol = "[\\$](bold fg:1)"
vimcmd_replace_symbol = "[\\$](bold fg:1)"
vimcmd_visual_symbol = "[\\$](bold fg:3)"

[line_break]
disabled = true

[directory]
style = "bold fg:3"
read_only = " "
read_only_style = "white"
truncation_length = 3

[cmd_duration]
disabled = true

[git_metrics]
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
style = "bold fg:11"

[status]
disabled = false
format = '[$symbol$status]($style) '
style = 'bold fg:1'
map_symbol = true
pipestatus = true
symbol = '󰅙 '
not_executable_symbol = '󰍶 '
not_found_symbol = '󰋗 '
sigint_symbol = '󰙦 '
signal_symbol = '󰝥 '
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style) '
pipestatus_segment_format = '[$symbol$status]($style)'

[bun]
symbol = '󰥚 '
format = '[$symbol($version)]($style) '
style = "bold fg:7"
[c]
symbol = " "
format = '[$symbol($version(-$name))]($style) '
style = "bold fg:10"
[dotnet]
symbol = '󰌛 '
format = '[$symbol($version)($tfm)]($style) '
style = "bold fg:3"
[gradle]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold fg:3"
[java]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold fg:1"
[lua]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold fg:4"
[nodejs]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold fg:5"
[package]
symbol = "󰏗 "
format = '[$symbol$version]($style) '
style = "bold fg:6"
[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
style = "bold fg:3"
[rust]
symbol = " "
format = '[$symbol($version)]($style) '
style = "bold fg:9"
