"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$status$all"

[battery]
disabled = true

[character] 
success_symbol = "[\\$](bold fg:4)"
error_symbol = "[\\$](bold fg:4)"
vimcmd_symbol = "[\\$](bold white)"
vimcmd_replace_one_symbol = "[\\$](bold fg:9)"
vimcmd_replace_symbol = "[\\$](bold fg:9)"
vimcmd_visual_symbol = "[\\$](bold fg:11)"

[line_break]
disabled = true

[username]
style_user = "bold fg:10"
style_root = "bold fg:9"
format = "[$user]($style) "
show_always = true
disabled = false

[hostname]
disabled = true

[directory]
style = "bold blue"
read_only = " "
read_only_style = "white"
truncation_length = 1

[cmd_duration]
disabled = true

[git_metrics]
disabled = false

[git_branch]
format = '[$symbol]($style)'

[status]
disabled = false
format = '[$symbol$status]($style) '
style = 'bold fg:9'
map_symbol = true
pipestatus = true
symbol = '󰅙 '
not_executable_symbol = '󰍶 '
not_found_symbol = '󰋗 '
sigint_symbol = '󰙦 '
signal_symbol = '󰝥 '

[bun]
format = '[$symbol]($style) '
[c]
symbol = " "
format = '[$symbol]($style) '
[dotnet]
symbol = '󰌛 '
format = '[$symbol($tfm)]($style) '
[gradle]
symbol = " "
format = '[$symbol]($style) '
[java]
symbol = " "
format = '[$symbol]($style) '
[lua]
symbol = " "
format = '[$symbol]($style) '
[nodejs]
symbol = " "
format = '[$symbol]($style) '
[package]
symbol = " "
format = '[$symbol]($style) '
[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(\($virtualenv\))]($style) '
[rust]
symbol = " "
format = '[$symbol]($style) '
