"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$status$username$hostname$battery$all"

[battery]
disabled = false

[[battery.display]]
threshold = 0
discharging_symbol = 'battery-'
charging_symbol = 'battery-'
style = 'fg:8'
[[battery.display]]
threshold = 20
discharging_symbol = 'battery-'
charging_symbol = 'battery-'
style = 'fg:8'
[[battery.display]]
threshold = 40
discharging_symbol = 'battery-'
charging_symbol = 'battery-'
style = 'fg:8'
[[battery.display]]
threshold = 60
discharging_symbol = 'battery-'
charging_symbol = 'battery-'
style = 'fg:8'
[[battery.display]]
threshold = 80
discharging_symbol = 'battery-'
charging_symbol = 'battery-'
style = 'fg:8'
[[battery.display]]
threshold = 100
discharging_symbol = 'battery-'
charging_symbol = 'battery-'
style = 'fg:8'

[character] 
success_symbol = "[\\$](bold blue)"
error_symbol = "[\\$](bold blue)"
vimcmd_symbol = "[\\$](bold white)"
vimcmd_replace_one_symbol = "[\\$](bold fg:9)"
vimcmd_replace_symbol = "[\\$](bold fg:9)"
vimcmd_visual_symbol = "[\\$](bold fg:11)"

[line_break]
disabled = true

[directory]
style = "bold blue"
read_only = " !"
read_only_style = "white"
truncation_length = 3

[cmd_duration]
disabled = true

[git_metrics]
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[status]
disabled = false
format = '[$symbol$status]($style) '
style = 'bold fg:9'
map_symbol = true
pipestatus = true
symbol = 'error '
not_executable_symbol = 'error '
not_found_symbol = 'error '
sigint_symbol = 'error '
signal_symbol = 'error '
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style) '
pipestatus_segment_format = '[$symbol$status]($style)'

[bun]
symbol = 'bun-'
format = '[$symbol($version)]($style) '
[c]
symbol = "c-"
format = '[$symbol($version(-$name))]($style) '
[dotnet]
symbol = 'csharp-'
format = '[$symbol($version)($tfm)]($style) '
[gradle]
symbol = "gradle-"
format = '[$symbol($version)]($style) '
[java]
symbol = "java-"
format = '[$symbol($version)]($style) '
[lua]
symbol = "lua-"
format = '[$symbol($version)]($style) '
[nodejs]
symbol = "node-"
format = '[$symbol($version)]($style) '
[package]
symbol = "version-"
format = '[$symbol$version]($style) '
[python]
symbol = "python-"
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
[rust]
symbol = "rust-"
format = '[$symbol($version)]($style) '

