[username]
style_user = "bold fg:9"
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = false
format = "[@]($style)[$hostname ]($style)"
style = "bold fg:9"
disabled = false
