local status, case = pcall(require, 'textcase')
if (not status) then return end

local snake = ':lua require(\'textcase\').current_word(\'to_snake_case\')<CR>'
local screaming_snake_case = ':lua require(\'textcase\').current_word(\'to_constant_case\')<CR>'

-- snake_case current word
vim.keymap.set('n', 'snake', snake)

-- SCREAMING_SNAKE_CASE current word
vim.keymap.set('n', 'snaake', screaming_snake_case)
vim.keymap.set('n', 'snaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
vim.keymap.set('n', 'snaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaake', screaming_snake_case)
