devices:
baseMouseSpeed: 1000.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0
startMouseSpeed: 0.0
mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: initial
  bindings:
    space: tap-hold-next space ; toggle-layer navigation ; 0
    capslock: leftctrl
    rightctrl: tap-hold-next rightctrl ; toggle-layer pseudo_hhkb ; 0
- name: navigation
  bindings:
    capslock: leftctrl
    s: move -1 0 
    d: move 0 1 
    f: move 0 -1 
    g: move 1 0 
    comma: button left
    dot: button right
    slash: button middle
    leftbrace: scroll down
    rightbrace: scroll up
    h: left
    j: down
    k: up
    l: right
    volumedown: brightnessdown
    volumeup: brightnessup
- name: pseudo_hhkb
  bindings:
    capslock: leftctrl
    a: volumedown
    s: volumeup
    d: mute
    # f: eject
    leftbrace: up
    semicolon: left
    apostrophe: right
    slash: down
    rightbrace: menu
    2: f1
    3: f2 
    4: f3
    5: f4
    6: f5 
    7: f6
    8: f7
    9: f8
    10: f9
    11: f10
    minus: f11
    equal: f12
