devices:
baseMouseSpeed: 1000.0
baseScrollSpeed: 20.0

mouseAccelerationTime: 200.0
mouseAccelerationCurve: 2.0
startMouseSpeed: 0.0
mouseDecelerationTime: 300.0
mouseDecelerationCurve: 3.0

layers:
- name: initial
  bindings:
    space: tap-hold-next space ; toggle-layer navigation ; 0
    scrolllock: brightnessdown
    pause: brightnessup
    capslock: leftctrl
- name: navigation
  bindings:
    capslock: leftctrl
    s: move -1 0 
    d: move 0 1 
    f: move 0 -1 
    g: move 1 0 
    comma: button left
    dot: button right
    slash: button middle
    leftbrace: scroll down
    rightbrace: scroll up
    h: left
    j: down
    k: up
    l: right
    2: leftctrl+f1
    3: leftctrl+f2
    4: leftctrl+f3
    5: leftctrl+f4
    6: leftctrl+f5
    7: leftctrl+f6
    8: leftctrl+f7
    9: leftctrl+f8
    10: leftctrl+f9
    11: leftctrl+f10
