#! /bin/sh

xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources
pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width 2
bspc config window_gap 20

bspc config focused_border_color "#ebdbb2"
bspc config normal_border_color "#a89983"
