#! /bin/sh

xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale ~/.config/wallpapers/gruvbox-dark.jpeg &
polybar &
picom &
gentoo-pipewire-launcher &

bspc monitor -d 'I' 'II' 'III' 'IV' 'V'

bspc config border_width 1
bspc config top_padding -20
bspc config window_gap 20
bspc config focused_border_color "#EBDBB2"
bspc config normal_border_color "#A89984" 

bspc rule -a Zathura state=tiled
