#! /bin/sh

# reload sxhkd
super + Escape
  pkill -USR1 -x sxhkd

# terminal emulator (kitty)
super + shift + Return
  kitty --single-instance

# application launcher
super + @space
  rofi -show drun -theme ~/.config/rofi/gruvbox-dark.rasi

# close or kill window
super + {_,shift+}w
  bspc node -{c,k}

# set master
super + Return
  bspc node -s biggest.window

# focus or swap in given direction
super + {_,shift + }{k,l,j,h}
  bspc node -{f,s} {north,east,south,west}

# uses script to resize window
super + alt + {k,l,j,h} 
  $HOME/.config/sxhkd/bspwm_resize {north,east,south,west}

# focuses spaces 1 - 9 or moves window to said space
super + {_,shift + }{1-9}
  bspc {desktop -f, node -d} '^{1-9}'

# fullscreens current window
super + f
  bspc node -t \~fullscreen

super + t 
  bspc node -t \~floating
