#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_destroyed active=yes action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse &> /dev/null || yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id) &> /dev/null"
sudo yabai --load-sa

yabai -m config                           \
  layout bsp                              \
  window_placement second_child           \
  top_padding    20                       \
  bottom_padding 20                       \
  left_padding   20                       \
  right_padding  20                       \
  window_gap     20                       \
  config auto_balance on                  \
  mouse_modifier fn                       \
  mouse_action1 move                      \
  mouse_action2 resize                    \
  focus_follows_mouse off                 \
  window_topmost on                       \
  window_shadow off                       \
  window_border on                        \
  window_border_width 1                   \
  window_border_radius -1                 \
  active_window_border_color 0xffebdbb2   \
  normal_window_border_color 0xffa89983   \
  window_animation_duration 0.2           \
  window_animation_frame_rate 60          \
  window_border_blur on                   \
  external_bar all:20:0

yabai -m space                            \
  1                                       \
  2                                       \
  3                                       \
  4                                       \
  5                                       

yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"
