after-startup-command = [ 
    'exec-and-forget defaults write com.doomlaser.cursorcerer idleHide -float 3',
    'exec-and-forget open -j -a ShowMeYourHotkeys',
    'exec-and-forget ./border',
]
start-at-login = true
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
default-root-container-layout = 'accordion'
default-root-container-orientation = 'horizontal'
key-mapping.preset = 'qwerty'

[gaps]
inner.horizontal = 20
inner.vertical =   20
outer.left =       20
outer.bottom =     20
outer.top =        10
outer.right =      20

[mode.main.binding]

    # All possible keys:
    # - Letters.        a, b, c, ..., z
    # - Numbers.        0, 1, 2, ..., 9
    # - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
    # - F-keys.         f1, f2, ..., f20
    # - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
    #                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
    #                   backspace, tab
    # - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
    # All possible modifiers: cmd, alt, ctrl, shift

    # All possible commands: https://nikitabobko.github.io/AeroSpace/commands

	cmd-h = []
	cmd-alt-h = []

    alt-cmd-ctrl-enter = 'exec-and-forget open -a kitty -n --args /run/current-system/sw/bin/tmux new-session -A -c ~/ -s main >/dev/null 2>&1'
    alt-cmd-ctrl-m = 'macos-native-fullscreen'

    alt-cmd-ctrl-left = 'focus left'
    alt-cmd-ctrl-down = 'focus down'
    alt-cmd-ctrl-up = 'focus up'
    alt-cmd-ctrl-right = 'focus right'

    alt-cmd-ctrl-1 = 'workspace 1'
    alt-cmd-ctrl-2 = 'workspace 2'
    alt-cmd-ctrl-3 = 'workspace 3'
    alt-cmd-ctrl-4 = 'workspace 4'
    alt-cmd-ctrl-5 = 'workspace 5'
    alt-cmd-ctrl-6 = 'workspace 6'
    alt-cmd-ctrl-7 = 'workspace 7'
    alt-cmd-ctrl-8 = 'workspace 8'
    alt-cmd-ctrl-9 = 'workspace 9'

    shift-alt-cmd-ctrl-1 = 'move-node-to-workspace 1'
    shift-alt-cmd-ctrl-2 = 'move-node-to-workspace 2'
    shift-alt-cmd-ctrl-3 = 'move-node-to-workspace 3'
    shift-alt-cmd-ctrl-4 = 'move-node-to-workspace 4'
    shift-alt-cmd-ctrl-5 = 'move-node-to-workspace 5'
    shift-alt-cmd-ctrl-6 = 'move-node-to-workspace 6'
    shift-alt-cmd-ctrl-7 = 'move-node-to-workspace 7'
    shift-alt-cmd-ctrl-8 = 'move-node-to-workspace 8'
    shift-alt-cmd-ctrl-9 = 'move-node-to-workspace 9'

# [[on-window-detected]]
# if.app-id = 'com.0804Team.KeyClu'
# run = ['layout floating']
