/**
 * Minimal LSP for Strudel .str / .std buffers.
 * Maps .str files to virtual .str.js paths so TypeScript can parse live-coding scripts.
 * Depends on strudel-core.d.ts (generated by generate-types.mjs).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";
import {
  createConnection,
  TextDocuments,
  TextDocumentSyncKind,
  CompletionItemKind,
} from "vscode-languageserver/node.js";
import { TextDocument } from "vscode-languageserver-textdocument";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const STRUDEL_DTS = path.join(__dirname, "strudel-core.d.ts");

if (!fs.existsSync(STRUDEL_DTS)) {
  console.error(`Missing ${STRUDEL_DTS}. Run :StrudelLspBuild first.`);
  process.exit(1);
}

const connection = createConnection(process.stdin, process.stdout);
const documents = new TextDocuments(TextDocument);

/** @type {Map<string, ts.IScriptSnapshot>} */
const snapshots = new Map();
/** @type {Map<string, string>} */
const versions = new Map();

snapshots.set(STRUDEL_DTS, ts.ScriptSnapshot.fromString(fs.readFileSync(STRUDEL_DTS, "utf8")));
versions.set(STRUDEL_DTS, "0");

function strudelTypesSnapshot() {
  return ts.ScriptSnapshot.fromString(fs.readFileSync(STRUDEL_DTS, "utf8"));
}

/**
 * @param {string} uri
 * @returns {string}
 */
function uriToPath(uri) {
  return decodeURIComponent(uri.replace(/^file:\/\//, ""));
}

/**
 * @param {string} uri
 * @returns {string}
 */
function toTsPath(uri) {
  const filePath = uriToPath(uri);
  if (filePath.endsWith(".str") || filePath.endsWith(".std")) {
    return `${filePath}.js`;
  }
  return filePath;
}

/**
 * @param {TextDocument} document
 */
function syncDocument(document) {
  const tsPath = toTsPath(document.uri);
  snapshots.set(tsPath, ts.ScriptSnapshot.fromString(document.getText()));
  versions.set(tsPath, String(Number(versions.get(tsPath) || "0") + 1));
}

/** @returns {ts.LanguageService} */
function createService() {
  /** @type {ts.LanguageServiceHost} */
  const host = {
    getScriptFileNames: () => [...snapshots.keys()],
    getScriptVersion: (fileName) => versions.get(fileName) || "0",
    getScriptSnapshot: (fileName) => {
      if (fileName === STRUDEL_DTS) {
        return strudelTypesSnapshot();
      }
      return snapshots.get(fileName);
    },
    getCurrentDirectory: () => __dirname,
    getCompilationSettings: () => ({
      allowJs: true,
      checkJs: false,
      noEmit: true,
      target: ts.ScriptTarget.ES2020,
      module: ts.ModuleKind.ESNext,
      lib: ["es2020", "dom"],
      skipLibCheck: true,
    }),
    getDefaultLibFileName: (options) => ts.getDefaultLibFilePath(options),
    fileExists: (fileName) => snapshots.has(fileName) || ts.sys.fileExists(fileName),
    readFile: (fileName) => {
      const snap = snapshots.get(fileName);
      if (snap) {
        return snap.getText(0, snap.getLength());
      }
      return ts.sys.readFile(fileName);
    },
    readDirectory: ts.sys.readDirectory,
    directoryExists: ts.sys.directoryExists,
    getDirectories: ts.sys.getDirectories,
  };

  return ts.createLanguageService(host, ts.createDocumentRegistry());
}

/** @param {ts.ScriptElementKind} kind */
function toCompletionKind(kind) {
  switch (kind) {
    case ts.ScriptElementKind.memberFunctionElement:
      return CompletionItemKind.Method;
    case ts.ScriptElementKind.callSignatureElement:
    case ts.ScriptElementKind.constructSignatureElement:
      return CompletionItemKind.Function;
    case ts.ScriptElementKind.memberVariableElement:
    case ts.ScriptElementKind.variableElement:
      return CompletionItemKind.Variable;
    case ts.ScriptElementKind.enumElement:
      return CompletionItemKind.Enum;
    case ts.ScriptElementKind.interfaceElement:
      return CompletionItemKind.Interface;
    case ts.ScriptElementKind.typeParameterElement:
      return CompletionItemKind.TypeParameter;
    default:
      return CompletionItemKind.Text;
  }
}

connection.onInitialize(() => ({
  capabilities: {
    textDocumentSync: TextDocumentSyncKind.Incremental,
    completionProvider: {
      triggerCharacters: [".", '"', "'", "(", " "],
      resolveProvider: true,
    },
    hoverProvider: true,
  },
}));

documents.onDidChangeContent((event) => {
  syncDocument(event.document);
});

documents.onDidOpen((event) => {
  syncDocument(event.document);
});

/** @param {ts.SymbolDisplayPart[] | string | undefined} parts */
function displayPartsToString(parts) {
  if (!parts) {
    return "";
  }
  if (typeof parts === "string") {
    return parts;
  }
  return parts.map((part) => part.text).join("");
}

/** @param {ts.JSDocTagInfo[] | undefined} tags */
function formatJSDocTags(tags) {
  if (!tags?.length) {
    return "";
  }

  const sections = [];
  for (const tag of tags) {
    const text = displayPartsToString(tag.text).trim();
    switch (tag.name) {
      case "example":
        sections.push(`@example\n\n\`\`\`javascript\n${text}\n\`\`\``);
        break;
      case "name":
        sections.push(`@name - ${text}`);
        break;
      case "param":
        sections.push(`@param ${text}`);
        break;
      default:
        if (text) {
          sections.push(`@${tag.name} ${text}`);
        }
        break;
    }
  }
  return sections.join("\n\n");
}

/** @param {{ documentation?: ts.SymbolDisplayPart[] | string, tags?: ts.JSDocTagInfo[] } | undefined} info */
function buildMarkdownDocumentation(info) {
  if (!info) {
    return undefined;
  }

  const description = displayPartsToString(info.documentation).trim();
  const tags = formatJSDocTags(info.tags);
  const combined = [description, tags].filter(Boolean).join("\n\n");
  return combined || undefined;
}

/** @param {ts.CompletionEntryDetails | undefined} details */
function documentationFromDetails(details) {
  return buildMarkdownDocumentation(details);
}

/** @param {ts.QuickInfo | undefined} info */
function documentationFromQuickInfo(info) {
  if (!info) {
    return undefined;
  }

  const markdown = buildMarkdownDocumentation(info);
  if (markdown) {
    return markdown;
  }

  const display = displayPartsToString(info.displayParts);
  if (display.trim() !== "" && !/^declare\b/.test(display.trim())) {
    return display;
  }
  return undefined;
}

/** @param {ReturnType<typeof createService>} service @param {string} tsPath @param {number} offset @param {ts.CompletionEntry} entry */
function completionItemFromEntry(service, tsPath, offset, entry) {
  const details = service.getCompletionEntryDetails(
    tsPath,
    offset,
    entry.name,
    undefined,
    undefined,
    undefined,
    entry
  );

  const documentation = documentationFromDetails(details);
  const detail = displayPartsToString(details?.displayParts)?.trim();
  const kind = entry.kind ? toCompletionKind(entry.kind) : CompletionItemKind.Text;

  return {
    label: entry.name,
    kind,
    detail: detail && !/^declare\b/.test(detail) ? detail : entry.name,
    documentation: documentation
      ? { kind: "markdown", value: documentation }
      : undefined,
  };
}

connection.onCompletion((params) => {
  const document = documents.get(params.textDocument.uri);
  if (!document) {
    return [];
  }

  syncDocument(document);
  const tsPath = toTsPath(params.textDocument.uri);
  const service = createService();
  const offset = document.offsetAt(params.position);
  const result = service.getCompletionsAtPosition(tsPath, offset, {});

  if (!result) {
    return [];
  }

  return result.entries.map((entry) => ({
    ...completionItemFromEntry(service, tsPath, offset, entry),
    data: {
      uri: params.textDocument.uri,
      position: params.position,
      entryKind: entry.kind,
      entrySource: entry.source,
    },
  }));
});

connection.onCompletionResolve((item) => {
  if (item.documentation || !item.data?.uri || !item.data?.position) {
    return item;
  }

  const document = documents.get(item.data.uri);
  if (!document) {
    return item;
  }

  syncDocument(document);
  const tsPath = toTsPath(document.uri);
  const service = createService();
  const offset = document.offsetAt(item.data.position);
  const resolved = completionItemFromEntry(service, tsPath, offset, {
    name: item.label,
    kind: item.data.entryKind,
    source: item.data.entrySource,
  });

  return {
    ...item,
    detail: resolved.detail,
    documentation: resolved.documentation,
    kind: resolved.kind,
  };
});

connection.onHover((params) => {
  const document = documents.get(params.textDocument.uri);
  if (!document) {
    return null;
  }

  syncDocument(document);
  const tsPath = toTsPath(params.textDocument.uri);
  const service = createService();
  const offset = document.offsetAt(params.position);
  const info = service.getQuickInfoAtPosition(tsPath, offset);

  if (!info) {
    return null;
  }

  const documentation = documentationFromQuickInfo(info);
  if (!documentation) {
    return null;
  }

  return {
    contents: { kind: "markdown", value: documentation },
  };
});

documents.listen(connection);
connection.listen();
