"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$status$username$hostname$battery$all"

[line_break]
disabled = true

[directory]
style = "bold fg:4"
read_only = "  "
read_only_style = "bold fg:8"
truncation_length = 3

[cmd_duration]
disabled = true

[git_metrics]
disabled = false

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '

[status]
disabled = false
format = '[$symbol](bold bg:9 bold fg:#000000)[ $status](bold bg:#000000 bold fg:9) '
style = 'bold fg:9'
map_symbol = true
pipestatus = true
symbol = ' ERROR '
not_executable_symbol = ' FAIL '
not_found_symbol = ' ERROR '
sigint_symbol = ' DEBUG '
signal_symbol = ' FATAL '
pipestatus_format = '\[$pipestatus\] => [$symbol$common_meaning$signal_name$maybe_int]($style) '
pipestatus_segment_format = '[$symbol$status]($style)'

[bun]
symbol = '󰳮 '
format = '[$symbol($version)]($style) '
[c]
symbol = " "
format = '[$symbol($version(-$name))]($style) '
[dotnet]
symbol = ' '
format = '[$symbol($version)($tfm)]($style) '
[gradle]
symbol = " "
format = '[$symbol($version)]($style) '
[java]
symbol = " "
format = '[$symbol($version)]($style) '
[lua]
symbol = " "
format = '[$symbol($version)]($style) '
[nodejs]
symbol = " "
format = '[$symbol($version)]($style) '
[package]
symbol = " "
format = '[$symbol$version]($style) '
[python]
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
[rust]
symbol = " "
format = '[$symbol($version)]($style) '

[battery]
disabled = false
unknown_symbol = '󱐥 '

[[battery.display]]
threshold = 0
discharging_symbol = '󰂎 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 10
discharging_symbol = '󰁺 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 20
discharging_symbol = '󰁻 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 30
discharging_symbol = '󰁼 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 40
discharging_symbol = '󰁽 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
[[battery.display]]
threshold = 50
discharging_symbol = '󰁾 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 60
discharging_symbol = '󰁿 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 70
discharging_symbol = '󰂀 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 80
discharging_symbol = '󰂁 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 90
discharging_symbol = '󰂂 '
charging_symbol = ' '
style = 'fg:8'
[[battery.display]]
threshold = 100
discharging_symbol = '󰁹 '
charging_symbol = ' '
style = 'fg:8'
