#!/bin/bash

ctrl - return : kitty ~/ --single-instance
ctrl - q : skhd --key "cmd - q"
ctrl - w : skhd --key "cmd - w"
ctrl - space : skhd --key "cmd - space"

ctrl - h : yabai -m window --focus west
ctrl - j : yabai -m window --focus south
ctrl - k : yabai -m window --focus north
ctrl - l : yabai -m window --focus east

ctrl + shift - h : yabai -m window --swap west
ctrl + shift - j : yabai -m window --swap south
ctrl + shift - k : yabai -m window --swap north
ctrl + shift - l : yabai -m window --swap east

ctrl + alt - h : yabai -m window --resize left:-20:0
ctrl + alt - j : yabai -m window --resize top:0:20
ctrl + alt - k : yabai -m window --resize top:0:-20
ctrl + alt - l : yabai -m window --resize left:20:0

ctrl - 0x1E : yabai -m window --toggle split
ctrl - 0x29 : yabai -m window --toggle native-fullscreen
ctrl - 0x27 : yabai -m window --toggle float && yabai -m window --grid 4:4:1:1:2:2
ctrl - 0x2C : librewolf

ctrl - 1 : yabai -m space --focus 1
ctrl - 2 : yabai -m space --focus 2
ctrl - 3 : yabai -m space --focus 3
ctrl - 4 : yabai -m space --focus 4
ctrl - 5 : yabai -m space --focus 5
ctrl - 6 : yabai -m space --focus 6
ctrl - 7 : yabai -m space --focus 7
ctrl - 8 : yabai -m space --focus 8
ctrl - 9 : yabai -m space --focus 9
ctrl - 0 : yabai -m space --focus 10

ctrl + shift - 1 : yabai -m window --space 1
ctrl + shift - 2 : yabai -m window --space 2
ctrl + shift - 3 : yabai -m window --space 3
ctrl + shift - 4 : yabai -m window --space 4
ctrl + shift - 5 : yabai -m window --space 5
ctrl + shift - 6 : yabai -m window --space 6
ctrl + shift - 7 : yabai -m window --space 7
ctrl + shift - 8 : yabai -m window --space 8
ctrl + shift - 9 : yabai -m window --space 9
ctrl + shift - 0 : yabai -m window --space 10
