SET SQLFORMAT ANSICONSOLE
SET HIGHLIGHTING ON
SET HIGHLIGHTING KEYWORD FOREGROUND RED
SET HIGHLIGHTING KEYWORD BOLD ON
SET HIGHLIGHTING IDENTIFIER FOREGROUND YELLOW
SET HIGHLIGHTING IDENTIFIER BOLD ON
SET HIGHLIGHTING STRING FOREGROUND GREEN
SET HIGHLIGHTING STRING BOLD ON
SET HIGHLIGHTING NUMBER FOREGROUND MAGENTA
SET HIGHLIGHTING NUMBER BOLD ON
SET HIGHLIGHTING COMMENT FOREGROUND WHITE
SET HIGHLIGHTING COMMENT BOLD ON
SET sqlprompt "@|bold  _USER|@@@|bold _CONNECT_IDENTIFIER|@@|bold :|@ "
