#!/usr/bin/env fish

function copy_art
    set album_path (mpc --format %file% | head -n 1 | sed 's/[^/]*$//')
    if test -n "~/Music/$path/cover.jpg"
        cp ~/Music/$album_path/cover.jpg ~/cover.jpg
    else
        echo "no cover art found"
    end
end

feh --reload 1 ~/cover.jpg & set feh_pid $last_pid

while true
    copy_art
    mpc idle >/dev/null
end
