#!/usr/bin/env fish

function copy_art
    set cover_art_path (mpc --format %file% | head -n 1 | sed 's/[^/]*$//' | xargs -I{} find ~/Music/{} -type f -iregex ".*\.\(jpg\|jpeg\|png\)\$" | head -n 1)
    if test -n "$cover_art_path"
        cp $cover_art_path ~/cover.jpg
    else
        echo "no cover art found"
    end
end

feh --reload 1 ~/cover.jpg & set feh_pid $last_pid

while true
    copy_art
    mpc idle >/dev/null
end
