#!/usr/bin/env bash

if [ $(ls -d /Volumes/*/ | wc -l) -gt 1 ]; then
    for disk in /dev/disk*; do
        if [[ $disk =~ [3-9]+$ ]]; then
            if [[ $disk =~ s[0-9]+$ ]]; then
                echo "Skipping $disk (ends with sX)..."
            else
                echo "Unmounting $disk..."
                diskutil unmountDisk $disk
            fi
        fi
    done
    osascript -e "display notification \"Drives unmounted, safe to undock\" with title \"Dock\""
else
    for disk in /dev/disk*; do
        if [[ $disk =~ [3-9]+$ ]]; then
            if [[ $disk =~ s[0-9]+$ ]]; then
                echo "Skipping $disk (ends with sX)..."
            else
                echo "Mounting $disk..."
                diskutil mountDisk $disk
            fi
        fi
    done
    osascript -e "display notification \"Drives mounted, safe to use\" with title \"Dock\""
fi
