#!/usr/bin/env sh

if [ "$#" -lt 1 ]; then
	echo "You need to provide at least one file as an argument."
	exit 1
fi

current_time=$(date "+%Y%m%d%H%M%S")
echo "Current Time : $current_time"

for file_name in "$@"; do
	new_fileName=$current_time-$file_name
	echo "New FileName: " "$new_fileName"
	cp "$file_name" "$new_fileName"
done

echo "You should see new files generated with timestamp on them.."
