#!/bin/bash
#Clear Terminal
clear
#Prompt for SU password to modprobe pcspkr
# echo "Modprobing required pcskpr..."
# sudo modprobe pcspkr
#Clear Terminal
clear
#Display Credits
echo "Running Beep Song:"
echo "Portal - Still Alive"
echo
echo "By:"
echo "Robert C. Maehl"
# Add Helper Name(s)
# echo ""
echo
echo "Beginning in:"
echo -n "3..."
sleep 1.0
echo -n "2..."
sleep 1.0
echo -n "1..."
sleep 1.0
echo -n "NOW"
#Clear Terminal
clear
echo -n "This "
beep -f 784 -l 200
echo -n "was "
beep -f 740 -l 200
echo -n "a "
beep -f 659 -l 200
echo -n "tri"
beep -f 659 -l 200
echo "umph."
beep -f 740 -l 200
sleep 0.8
#New Line
echo -n "I'm "
beep -f 784 -l 200
echo -n "making "
beep -f 740 -l 200
echo -n "a "
beep -f 659 -l 200
echo -n "note "
beep -f 659 -l 200
sleep 0.3
echo "here: "
beep -f 740 -l 200
#New Line
echo -n "HUGE "
beep -f 587 -l 200
sleep 0.3
echo -n "SUC"
beep -f 659 -l 200
echo "CESS."
beep -f 440 -l 200
sleep 0.8
#New Line
echo -n "It's "
beep -f 440 -l 200
echo -n "hard "
beep -f 659 -l 300
echo -n "to "
beep -f 740 -l 200
echo -n "o"
beep -f 784 -l 300
echo -n "ver"
beep -f 659 -l 300
echo "state "
beep -f 554 -l 200
sleep 0.1
#New Line
echo -n "my "
beep -f 587 -l 200
echo -n "sat"
beep -f 659 -l 300
sleep 0.1
echo -n "is"
beep -f 440 -l 300
echo -n "fac"
beep -f 440 -l 200
echo "tion."
beep -f 740 -l 200
echo
#Display Image
sleep 1
echo "                .,-:;//;:=,                  "
echo "            . :H@@@MM@M#H/.,+%;,             "
echo "         ,/X+ +M@@M@MM%=,-%HMMM@X/,          "
echo "       -+@MM; #M@@MH+-,;XMMMM@MMMM@+-        "
echo "      ;@M@@M- XM@X;. -+XXXXXHHH@M@M#@/.      "
echo "    ,%MM@@MH ,@%=            .---=-=:=,.     "
echo "    =@#@@@MX .,              -%HX##%%%+;     "
echo "   =-./@M@M$                  .;@MMMM@MM:    "
echo "   X@/ -#MM/                    .+MM@@@M$    "
echo "  ,@M@H: :@:                    . =X#@@@@-   "
echo "  ,@@@MMX, .                    /H- ;@M@M=   "
echo "  .H@@@@M@+,                    %MM+..%#$.   "
echo "   /MMMM@MMH/.                  XM@MH; =;    "
echo "    /%+%#XHH@$=              , .H@@@@MX,     "
echo "     .=--------.           -%H.,@@@@@MX,     "
echo "     .%MM@@@HHHXX###%+= .:#MMX =M@@MM%.      "
echo "       =XMMM@MM@MM#H;,-+HMM@M+ /MMMX=        "
echo "         =%@M@M#@$-.=#@MM@@@M; %M%=          "
echo "           ,:+$+-,/H#MMMMMMM@= =,            "
echo "                 =++%%%%+/:-.                "
echo
echo -n "Ap"
beep -f 784 -l 200
echo -n "er"
beep -f 740 -l 200
echo -n "ture "
beep -f 659 -l 200
echo -n "Sci"
beep -f 659 -l 200
echo "ence"
beep -f 740 -l 200
sleep 0.8
#New Line
echo -n "We "
beep -f 784 -l 200
echo -n "do what "
beep -f 740 -l 200
echo -n "we "
beep -f 659 -l 200
echo "must "
beep -f 659 -l 200
sleep 0.3
#New Line
echo -n "be"
beep -f 740 -l 200
echo -n "cause "
beep -f 587 -l 200
sleep 0.3
echo -n "we "
beep -f 659 -l 200
echo "can."
beep -f 440 -l 200
sleep 0.8

echo -n "For "
beep -f 659 -l 300
echo -n "the "
beep -f 740 -l 200
echo -n "good "
beep -f 784 -l 300
echo -n "of "
beep -f 659 -l 200
echo -n "all "
beep -f 554 -l 300
echo -n "of "
beep -f 587 -l 200
echo "us."
beep -f 659 -l 400
sleep 0.1
#New Line
echo -n "Ex"
beep -f 440 -l 200
echo -n "cept "
beep -f 587 -l 200
echo -n "the "
beep -f 659 -l 200
echo -n "ones "
beep -f 698 -l 200
echo -n "who "
beep -f 659 -l 200
echo -n "are "
beep -f 587 -l 200
echo "dead."
beep -f 523 -l 200
sleep 0.4
#Blank Line
echo
#New Line
beep -f 440 -l 200
echo -n "But "
beep -f 466 -l 300
echo -n "there's "
beep -f 523 -l 300
echo -n "no "
beep -f 698 -l 200
echo -n "sense "
sleep 0.1
beep -f 659 -l 200
echo -n "cry"
beep -f 587 -l 200
echo "ing "
beep -f 587 -l 200
#New Line
echo -n "over "
beep -f 523 -l 200
sleep 0.05
beep -f 587 -l 200
echo -n "every "
beep -f 523 -l 200
echo -n "mis"
sleep 0.05
beep -f 523 -l 300
echo "take."
sleep 0.05
beep -f 523 -l 200
sleep 0.2
#New Line
beep -f 440 -l 200
echo -n "You "
beep -f 466 -l 300
echo -n "just "
beep -f 523 -l 300
echo -n "keep "
beep -f 698 -l 200
echo -n "on "
sleep 0.1
beep -f 783 -l 200
echo -n "try"
beep -f 698 -l 200
echo "ing "
beep -f 659 -l 250
#New Line
echo -n "til "
beep -f 587 -l 200
echo -n "you "
beep -f 587 -l 200
echo -n "run "
beep -f 659 -l 200
echo -n "out "
beep -f 698 -l 300
echo -n "of "
sleep 0.05
beep -f 698 -l 300
echo "cake."
sleep 0.1
#New Line
echo -n "And "
beep -f 783 -l 200
echo -n "the "
beep -f 880 -l 200
echo -n "Sci"
beep -f 932 -l 200
echo -n "ence "
beep -f 932 -l 200
echo -n "gets "
beep -f 880 -l 200
sleep 0.05
echo "done."
beep -f 783 -l 300
#New Line
echo -n "And "
beep -f 698 -l 200
echo -n "you "
beep -f 783 -l 200
echo -n "make "
beep -f 880 -l 200
echo -n "a "
beep -f 880 -l 200
echo -n "neat "
beep -f 783 -l 200
sleep 0.05
echo "gun."
beep -f 698 -l 300
sleep 0.1
#New Line
#The Notes are off starting around here
echo -n "for "
beep -f 587 -l 200
echo -n "the "
beep -f 523 -l 200
echo -n "peo"
beep -f 587 -l 200
echo -n "ple "
beep -f 698 -l 200
echo -n "who "
beep -f 698 -l 200
echo "are"
beep -f 659 -l 300
sleep 0.05
#New Line
echo -n "still "
beep -f 659 -l 200
echo -n "a"
beep -f 739 -l 100
echo "live."
beep -f 739 -l 400
#Need more lyrics and beeps (I have the ascii art already_

