#!/usr/bin/env bash

output_file="$(date '+%Y-%m-%d').txt"

trap 'kill $PID; exit' INT

pactl list short sources | awk '{print $2}'

echo

songrec listen --audio-device alsa_output.pci-0000_c1_00.1.hdmi-stereo-extra2.monitor >>"$output_file"
