#!/usr/bin/env fish

if type --no-functions --query lsd
  echo -e "lsd \033[1;32m✔\033[0m"
else
  echo -e "lsd \033[1;31m✘\033[0m"
end

if type --no-functions --query rg
  echo -e "ripgrep \033[1;32m✔\033[0m"
else
  echo -e "ripgrep \033[1;31m✘\033[0m"
end

if type --no-functions --query flashfetch
  echo -e "fastfetch \033[1;32m✔\033[0m"
else
  echo -e "fastfetch \033[1;31m✘\033[0m"
end

if type --no-functions --query rip
  echo -e "rm-improved \033[1;32m✔\033[0m"
else
  echo -e "rm-improved \033[1;31m✘\033[0m"
end


if type --no-functions --query qrencode
  echo -e "qrencode \033[1;32m✔\033[0m"
else
  echo -e "qrencode \033[1;31m✘\033[0m"
end

if type --no-functions --query nvim
  echo -e "nvim \033[1;32m✔\033[0m"
else
  echo -e "nvim \033[1;31m✘\033[0m"
end

if type --no-functions --query transmission-remote
  echo -e "transmission \033[1;32m✔\033[0m"
else
  echo -e "transmission \033[1;31m✘\033[0m"
end

if type --no-functions --query mpv
  echo -e "mpv \033[1;32m✔\033[0m"
else
  echo -e "mpv \033[1;31m✘\033[0m"
end

if type --no-functions --query onefetch
  echo -e "onefetch \033[1;32m✔\033[0m"
else
  echo -e "onefetch \033[1;31m✘\033[0m"
end

if type --no-functions --query bat
  echo -e "bat \033[1;32m✔\033[0m"
else
  echo -e "bat \033[1;31m✘\033[0m"
end

if type --no-functions --query duf
  echo -e "duf \033[1;32m✔\033[0m"
else
  echo -e "duf \033[1;31m✘\033[0m"
end

if type --no-functions --query scrcpy
  echo -e "scrcpy \033[1;32m✔\033[0m"
else
  echo -e "scrcpy \033[1;31m✘\033[0m"
end

if type --no-functions --query starship
  echo -e "starship \033[1;32m✔\033[0m"
else
  echo -e "starship \033[1;31m✘\033[0m"
end

if type --no-functions --query zoxide
  echo -e "zoxide \033[1;32m✔\033[0m"
else
  echo -e "zoxide \033[1;31m✘\033[0m"
end

if type --no-functions --query zathura
  echo -e "zathura \033[1;32m✔\033[0m"
else
  echo -e "zathura \033[1;31m✘\033[0m"
end
