#!/bin/bash

cd ~/.config/fish/fish/

if [ -f coreutils.fish ]; then
	rm coreutils.fish
fi
touch coreutils.fish

for i in $(
	coreutils |
		sed -e 1,6d |
		tr -d " \t\n\r" |
		tr "," "\n" |
		awk NF
); do
	if [ "$i" != "[" ] && [ "$i" != "test" ]; then
		echo "function $i" >>coreutils.fish
		echo "coreutils $i \$argv" >>coreutils.fish
		echo "end" >>coreutils.fish
	fi
done
