#!/bin/bash

source() {
	(
		echo
		echo 'eval "$($(which brew) shellenv)"'
	) >>/Users/raf/.zprofile
	eval "$($(which brew) shellenv)"
}

if ! command -v brew; then
	echo "REPLICATE: grabbing brew"
	bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

echo "REPLICATE: synchronising with .packages/brew"
source
brew tap homebrew/cask-fonts
brew install --no-quarantine $(cat .packages/brew)
source
brew install --HEAD felixkratz/formulae/borders
brew services start borders
brew services restart borders
yabai --start-service
yabai --restart-service
skhd --start-service
skhd --restart-service
open -a karabiner-elements
killall Karabiner-Elements
