#!/bin/bash

source() {
  (
    echo
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"'
  ) >>/Users/raf/.zprofile
  eval "$(/opt/homebrew/bin/brew shellenv)"
}

if ! command -v brew; then
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

source
brew tap homebrew/cask-fonts
brew install --no-quarantine $(cat .packages/brew)
source
yabai --start-service
skhd --start-service
open -a karabiner-elements
