#!/bin/bash

source() {
  (
    echo
    echo 'eval "$($(which brew) shellenv)"'
  ) >>/Users/raf/.zprofile
  eval "$($(which brew) shellenv)"
}

if ! command -v brew; then
  bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

source
brew tap homebrew/cask-fonts
brew install --no-quarantine $(cat .packages/brew)
source
brew install --HEAD felixkratz/formulae/fyabai
brew services restart yabai
skhd --start-service
open -a karabiner-elements
