#!/bin/bash

HOSTNAME=$(hostname -s | tr A-z a-z)

echo "REPLICATE: grabbing portage tree based on machine name"
rm -rf /etc/portage
git clone https://github.com/rraafays/$HOSTNAME /etc/portage

echo "REPLICATE: synchronising packages with database"
emerge --sync

echo "REPLICATE: synchronising world file"
cp .packages/emerge /var/lib/portage/world
emerge --quiet --update --deep --newuse @world

echo "REPLICATE: checking for package news"
eselect news read

echo "REPLICATE: applying sudo => doas symlink"
ln -s $(which doas) /bin/sudo

echo "REPLICATE: applying userchrome"
for dir in $HOME/.librewolf/*; do mkdir -- "$dir/chrome"; done
cp $HOME/.config/etc/modifications/librewolf/userChrome.css $HOME/.librewolf/*/chrome/
