#!/bin/bash

rm -rf /etc/portage
git clone https://github.com/rraafays/$HOSTNAME /etc/portage
emerge --sync
emerge --quiet --update --deep --newuse @world
emerge --verbose --noreplace $(cat .packages/emerge)
rc-update add elogind default
rc-update add dbus default
rc-service elogind start
rc-service dbus start
eselect news read
