[username]
style_user = "bold fg:10"
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = false
format = "[@]($style)[$hostname ]($style)"
style = "bold fg:10"
disabled = false

[character]
success_symbol = "[\\$](bold fg:4)"
error_symbol = "[\\$](bold fg:4)"
vimcmd_symbol = "[\\$](bold #525252)"
vimcmd_replace_one_symbol = "[\\$](bold fg:9)"
vimcmd_replace_symbol = "[\\$](bold fg:9)"
vimcmd_visual_symbol = "[\\$](bold #FFE97B)"
