#!/bin/bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

yabai -m config \
	layout bsp \
	window_placement second_child \
	window_zoom_persist on \
	top_padding 20 \
	bottom_padding 20 \
	left_padding 20 \
	right_padding 20 \
	window_gap 20 \
	config auto_balance on \
	mouse_modifier shift \
	mouse_action1 move \
	mouse_action2 resize \
	focus_follows_mouse off \
	mouse_follows_focus true \
	window_topmost off \
	window_shadow off \
	window_animation_duration 0 \
	window_animation_frame_rate 60 \
	window_border_blur off \
	external_bar all:0:0

yabai -m space 1 2 3 4 5 6 7 8 9 10
borders active_color=0xffEBDBB2 inactive_color=0xff928373 width=3.0 2>/dev/null 1>&2 &
