player: mpd
mpd:
  address: 127.0.0.1:6600
  password: ""
host: lyricsapi.vercel.app
ignoreErrors: true
timerInterval: 200
updateInterval: 2000
style:
  hAlignment: center
  before:
    background: ""
    foreground: "7"
    bold: false
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  current:
    background: ""
    foreground: ""
    bold: true
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
  after:
    background: ""
    foreground: "7"
    bold: false
    italic: false
    undeline: false
    strikethrough: false
    blink: false
    faint: false
pipe:
  length: 0
  overflow: word
  address: 127.0.0.1:6600
  password: ""
mopidy:
  address: 127.0.0.1:6680
mpris:
  players: []
